GET http://localhost:24529/simpleshortener_admin_api/list
Accept: application/json
Username: IT
Password: ASecurePassword

###

POST http://localhost:24529/simpleshortener_admin_api/add
Content-Type: application/json
Username: IT
Password: ASecurePassword

{
    "link": "shorturl",
    "destination": "https://example.com"
}

###

GET http://localhost:24529/simpleshortener_admin_api/list
Accept: application/json
Username: IT
Password: ASecurePassword

###

POST http://localhost:24529/simpleshortener_admin_api/delete
Content-Type: application/json
Username: IT
Password: ASecurePassword

{
    "link": "shorturl"
}

###

POST http://localhost:24529/simpleshortener_admin_api/add
Content-Type: application/json
Username: IT
Password: ASecurePassword

{
    "link": "shorturl",
    "destination": "https://example.com"
}

###

POST http://localhost:24529/simpleshortener_admin_api/edit
Content-Type: application/json
Username: IT
Password: ASecurePassword

{
    "link": "shorturl",
    "destination": "https://example.org"
}

###

GET http://localhost:24529/simpleshortener_admin_api/list
Accept: application/json
Username: IT
Password: ASecurePassword

###

POST http://localhost:24529/simpleshortener_admin_api/delete
Content-Type: application/json
Username: IT
Password: ASecurePassword

{
  "link": "shorturl"
}

###

POST http://localhost:24529/simpleshortener_admin_api/edit
Content-Type: application/json
Username: IT
Password: ASecurePassword

{
  "link": "nonexistent",
  "destination": "https://example.com"
}

###

GET http://localhost:24529/simpleshortener_admin_api/list
Accept: application/json
Username: IT
Password: ASecurePassword

###